const gallery = {
    display: "flex",
    alignItems: "center",
    position: "relative",
    height: "clamp(100px, calc(25vw + 50px), 55rem)",
    overflow: "hidden",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    backgroundOrigin: "content-box",
    backgroundSize: "cover",
    div: {
        display: "flex",
        visibility: "hidden",
        alignItems: "center",
        justifyContent: "center",
        position: "absolute",
        fontSize: "3rem",
        top: "0px",
        left: "0px",
        right: "0px",
        bottom: "0px",
        transition: ".3s ease",
        opacity: 0,
        zIndex: 1,
        a: {
            padding: 1,
            margin: 1,
            color: "white",
            lineHeight: 0,
            bg: "accent",
        },
    },
    "::before": {
        content: '""',
        position: "absolute",
        top: "0px",
        left: "0px",
        right: "0px",
        width: "100%",
        height: "100%",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        opacity: 0,
        transition: "0.2s ease",
    },
    "::after": {
        content: '""',
        position: "absolute",
        top: "-74rem",
        left: "150rem",
        right: "0px",
        width: "30rem",
        height: "180rem",
        transform: "rotate(-45deg)",
        transition: ".7s ease",
        backgroundColor: "rgba(255, 255, 255, 0.5)",
    },
    "&:hover": {
        div: {
            visibility: "visible",
            opacity: 1,
        },
        "::before": {
            opacity: 1,
        },
        "::after": {
            left: "-100rem",
        },
    },
    "@media screen and (min-width:  1440px)": {},
};
export default gallery;